ToDoApp/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :developers, controller: :developers
  resources :tasks, controller: :tasks do
    get :start
    get :finish
  end
  resources :projects, controller: :projects
  get 'users/dashboard'
	devise_scope :user do
    authenticated :user do
      root 'users#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

ToDoApp/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.is_admin?
      can :manage, :all
    end

    if user.is_developer?
      can :manage, Task
      cannot :read, Project
      can :manage, User, id: @user.id
    end
  end
end

ToDoApp/app/models/admin.rb
class Admin < User
  has_many :projects
end

ToDoApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ToDoApp/app/models/developer.rb
class Developer < User
  has_many :tasks

  def projects
    Project.where(id: tasks.pluck(:project_id).uniq)
  end

  def new_tasks
    tasks.where(status: 'new')
  end

  def in_progress_tasks
    tasks.where(status: 'InProgress')
  end

  def done_tasks
    tasks.where(status: 'Done')
  end
end

ToDoApp/app/models/project.rb
class Project < ApplicationRecord

  # has_and_belongs_to_many :developers, class_name: 'Developer', association_foreign_key: 'user_id', join_table: 'assigned_projects_developers'
  has_many :tasks, dependent: :destroy

  belongs_to :admin

  validates :name, presence: :true, uniqueness: true
  def self.search(search)
    where("name LIKE ?", "%#{search}%").order("created_at DESC")
  end

  def developer_count
    tasks.pluck(:developer_id).uniq.count
  end

  def new_tasks
    tasks.where(status: 'new')
  end

  def in_progress_tasks
    tasks.where(status: 'InProgress')
  end

  def done_tasks
    tasks.where(status: 'Done')
  end
end

ToDoApp/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :developer
  validates :name, presence: :true, uniqueness: {scope: :project_id,  case_sensitive: false}
  validates :status, inclusion: { in: %w(new InProgress Done),
    message: "%{value} is not a valid status" }
  validates :developer, :project, presence: :true
end

ToDoApp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, format: {with: Devise.email_regexp}
  validates :email, presence: :true, uniqueness: true
  validates :name, presence: :true

	def is_admin?
    type == 'Admin'
  end

  def is_developer?
    type == 'Developer'
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%").order("created_at DESC")
  end
end

ToDoApp/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

ToDoApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :load_current_user
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address])
  end

  def load_current_user
  	@current_user = current_user
  end
end

ToDoApp/app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :load_developer, only: [:show, :edit, :update, :destroy]
  def index
    @developers = params[:search].blank? ? Developer.all : Developer.search(params[:search])
  end

  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(developer_params)
    @developer.password = '123456'
    if @developer.save
      redirect_to @developer
    else
      p @developer.errors
      render 'new'
    end
  end

  def update
    if @developer.update(developer_params)
      redirect_to developers_path
    else
      p @developer.errors
      render 'edit'
    end
  end

  def destroy
    @developer.destroy

    redirect_to developers_path
  end

  private
  def developer_params
    params.require(:developer).permit(:name, :email, :address)
  end

  def load_developer
    @developer = Developer.find_by(id: params[:id])
  end
end

ToDoApp/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_project, only: [:show, :edit, :update, :destroy]
  def index
    if current_user.is_admin?
      @projects = params[:search].blank? ? current_user.projects : @current_user.projects.search(params[:search])
    else current_user.is_developer?
      @projects = params[:search].blank? ? current_user.projects.all : current_user.projects.search(params[:search])
    end
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build project_params
    @project.developer_ids = params[:project][:developer_ids].reject(&:empty?) if params[:project][:developer_ids]
    if @project.save
      flash[:success] = "project created successfully" 
      redirect_to projects_path
    else
      p @project.errors
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      p @project.errors
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
  def load_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :start_date,:technology)
  end
end

ToDoApp/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_task, only: [:show, :edit, :update, :destroy]
  def index
    project_ids = current_user.projects.pluck(:id)
    @tasks = Task.where(project_id: project_ids)
  end

  def new
    @task = Task.new
    @projects = current_user.projects
    @developers = Developer.all
  end

  def create
    @task = Task.new task_params
    if @task.save
      flash[:success] = "Task created successfully" 
      redirect_to tasks_path
    else
      p @task.errors
      render 'new'
    end
  end

  def edit
    @projects = current_user.projects
    @developers = Developer.all
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      p @task.errors
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def start
    @task = Task.find(params['task_id'])
    @task.update(status: 'InProgress')
    redirect_to tasks_path
  end

  def finish
    @task = Task.find(params['task_id'])
    @task.update(status: 'Done', end_date: Date.today)
    redirect_to tasks_path
  end
  private
  def load_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :start_date,:description, :project_id, :developer_id)
          .merge(params.permit(:project_id, :developer_id))
  end

end

ToDoApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @developers = Developers.all if current_user.is_admin?
  end

  def dashboard
    @current_user = current_user
    @developers = Developer.all if current_user.is_admin?
    @projects = get_projects
    project_ids = @projects.pluck(:id)
    @new_tasks_count = Task.where(project_id: project_ids, status: 'new').count
    @in_progress_tasks_count = Task.where(project_id: project_ids, status: 'InProgress').count
    @done_tasks_count = Task.where(project_id: project_ids, status: 'Done').count
  end

  def get_projects
    current_user.is_admin? ? Admin.find(current_user.id).projects : Developer.find(current_user.id).projects
  end
end

ToDoApp/app/helpers/application_helper.rb
module ApplicationHelper
end

ToDoApp/app/views/developers/_form.html.haml
= f.label :name
%br/
= f.text_field :name, autocomplete: "name"
%br/
= f.label :address
%br/
= f.text_field :address
%br/
= f.label :email
%br/
= f.email_field :email, autofocus: true, autocomplete: "email"
%br/
(Default password will be 123456)
%br/
%br/
.actions
= f.submit "Add", class: "btn btn-success"
= link_to "Cancel", :back, {:class=>"btn btn-default"}

ToDoApp/app/views/developers/edit.html.haml
%h2 Edit Developer
= form_for(@developer) do |f|
  = render 'form', f: f

ToDoApp/app/views/developers/index.html.haml
%h1 Developers
= link_to "Add new Devepoler", new_developer_path, class: 'btn btn-success'
%br
%br
%h3 Search Deveplers
= form_for(:users, url: developers_path, :method => "get", id: "search-form") do
  = text_field_tag :search, params[:search], placeholder: "Search developer"
  = submit_tag "Search", name: nil
- unless @developers.present?
  .alert.alert-warning
    - if (params[:search])
      There are no Developers matching '#{params[:search]}'
    - else
      There are no Developers
- else
  - i = 1
  %table.table.table-blue
    %th SR. no.
    %th Name
    %th Address
    %th Email
    %th Delete
    %th Update
    - @developers.each do |developer|
      %tr
        %td= i
        %td= link_to(developer.name, developer_path(developer))
        %td= developer.address
        %td= developer.email
        %td= link_to 'Delete', developer_path(developer),  |
            method: :delete,                    |
            data: { confirm: 'Are you sure?' }, |
            class: "btn btn-danger"             |
        %td= link_to 'Edit', edit_developer_path(developer), class: 'btn btn-warning'
        
        - i=i+1

ToDoApp/app/views/developers/new.html.haml
%h2 New Developer
= form_for(@developer) do |f|
  = render 'form', f: f

ToDoApp/app/views/developers/show.html.haml
= @developer.name

ToDoApp/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %script{:src => "https://www.gstatic.com/charts/loader.js", :type => "text/javascript"}
    %title ToDoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    %h3
      %u
        %b
          Welcome
          = @current_user&.name
    .container
      .btn-group
        = link_to 'Home', authenticated_root_path, class: 'btn btn-primary'
        = link_to 'Developers', developers_path, class: 'btn btn-primary' if @current_user.present? && @current_user.is_admin?
        = link_to 'Projects', projects_path, class: 'btn btn-primary' if @current_user.present? && @current_user.is_admin?
        = link_to 'Tasks', tasks_path, class: 'btn btn-primary' if @current_user.present? && @current_user.projects.present?
        = link_to 'Add Project', new_project_path, class: 'btn btn-primary' if @current_user.present? && @current_user.is_admin?
        = link_to 'Add Tasks', new_task_path, class: 'btn btn-primary' if @current_user.present? && @current_user.is_admin?
        = link_to 'Edit', edit_user_registration_path, method: :get, class: 'btn btn-primary' if @current_user.present?
        = link_to "Logout #{@current_user.name} ", destroy_user_session_path, method: :delete, class: 'btn btn-danger float-right' if @current_user.present?
    .container
    .jumbotron
      = yield

ToDoApp/app/views/projects/_form.html.haml
= f.label :name
%br/
= f.text_field :name, autocomplete: "name", required: true
%br/
= f.label :technology
%br/
= f.text_field :technology, required: true
%br/
= f.label :start_date
%br/
= f.date_field :start_date
%br/
%br/
.actions
= f.submit "Add", class: "btn btn-success"
= link_to "Cancel", :back, {:class=>"btn btn-default"}

ToDoApp/app/views/projects/edit.html.haml
%h2 Edit Project
= form_for(@project) do |f|
  = render 'form', f: f

ToDoApp/app/views/projects/index.html.haml
%h1 Projects
= link_to "Add new Project", new_project_path, class: 'btn btn-success'
%br
%br
%h3 Search Projects
= form_for(:projects, url: projects_path, :method => "get", id: "search-form") do
  = text_field_tag :search, params[:search], placeholder: "Search project"
  = submit_tag "Search", name: nil
- unless @projects.present?
  .alert.alert-warning
    - if (params[:search])
      There are no Projects matching '#{params[:search]}'
    - else
      There are no Projects
- else
  - i = 1
  %table.table.table-blue
    %th SR. no.
    %th Name
    %th Start Date
    %th End Date
    %th Technology
    %th #Tasks
    %th #Developers
    %th Delete
    %th Update
    - @projects.each do |project|
      %tr
        %td= i
        %td= link_to(project.name, project_path(project))
        %td= project.start_date
        %td= project.end_date
        %td= project.technology
        %td= project.tasks.count
        %td= project.developer_count
        %td= link_to 'Delete', project_path(project),  |
            method: :delete,                    |
            data: { confirm: 'Are you sure?' }, |
            class: "btn btn-danger"             |
        %td= link_to 'Edit', edit_project_path(project), class: 'btn btn-warning'
        
        - i=i+1

ToDoApp/app/views/projects/new.html.haml
%h2 New Project
= form_for(@project) do |f|
  = render 'form', f: f

ToDoApp/app/views/projects/show.html.haml
%h3
	%b= @project.name
%h4
	%br/
	(
	= @project.start_date
	= '-'
	- if @project.end_date
		= "#{@project.end_date})"
	- else
		= 'Not yet closed)'
	%br/
	Technology: 
	= @project.technology
%br

ToDoApp/app/views/tasks/_form.html.haml
= f.label :name
%br/
= f.text_field :name, autocomplete: "name"
%br/
= f.label :description
%br/
= f.text_area :description
%br/
%br/
= f.label :start_date
%br/
= f.date_field :start_date
%br/
= f.label :project
%br/
%select{ :name => "project_id" }
  - @projects.each do |project|
    %option{:value => project.id}= project.name


%br/
= f.label :assign_developer
%br/
%select{ :name => "developer_id" }
  - @developers.each do |developer|
    %option{:value => developer.id}= developer.name
%br/

%br/
%br/
.actions
= f.submit "Add", class: "btn btn-success"
= link_to "Cancel", :back, {:class=>"btn btn-default"}

ToDoApp/app/views/tasks/edit.html.haml
%h2 Edit Task
= form_for(@task) do |f|
  = render 'form', f: f

ToDoApp/app/views/tasks/index.html.haml
%h1 Tasks
= link_to "Add new task", new_task_path, class: 'btn btn-success'
%br
%br
%h3 Search Tasks
= form_for(:tasks, url: tasks_path, :method => "get", id: "search-form") do
  = text_field_tag :search, params[:search], placeholder: "Search task"
  = submit_tag "Search", name: nil
- unless @tasks.present?
  .alert.alert-warning
    - if (params[:search])
      There are no tasks matching '#{params[:search]}'
    - else
      There are no tasks
- else
  - i = 1
  %table.table.table-blue
    %th SR. no.
    %th Name
    %th Project
    - if @current_user.is_admin?
      %th Assigned To
    %th Start Date
    %th End Date
    %th Description
    %th Current Status
    -if @current_user.is_admin?
      %th Delete
      %th Update
    - else
      %th Action
    - @tasks.each do |task|
      %tr
        %td= i
        %td= link_to(task.name, task_path(task))
        %td= task.project.name
        - if @current_user.is_admin?
          %td= task.developer.name
        %td= task.start_date
        %td= task.end_date
        %td= task.description
        %td= task.status.capitalize
        - if @current_user.is_admin?
          %td= link_to 'Delete', task_path(task),  |
            method: :delete,                    |
            data: { confirm: 'Are you sure?' }, |
            class: "btn btn-danger"             |
          %td= link_to 'Edit', edit_task_path(task), class: 'btn btn-warning'
        - else
          - if(task.status.capitalize == 'New')
            %td= link_to 'Satrt', task_start_path(task), class: 'btn btn-success'
          - elsif(task.status.capitalize == 'Inprogress')
            %td= link_to 'Finish', task_finish_path(task), class: 'btn btn-danger'
          - else
            %td= 'DONE'
        - i=i+1

ToDoApp/app/views/tasks/new.html.haml
%h2 New Task
= form_for(@task) do |f|
  = render 'form', f: f

ToDoApp/app/views/users/dashboard.html.haml
:javascript
  // Load the Visualization API and the corechart package.
  google.charts.load('current', {'packages':['corechart']});

  // Set a callback to run when the Google Visualization API is loaded.
  google.charts.setOnLoadCallback(drawChart);

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart() {
  var chart_div = document.getElementById('chart_div');
  var new_tasks_count = parseInt(chart_div.dataset.new)
  var in_progress_tasks_count = parseInt(chart_div.dataset.inprogress)
  var done_tasks_count = parseInt(chart_div.dataset.done)
    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Topping');
    data.addColumn('number', 'Slices');
    data.addRows([
      ['New', new_tasks_count],
      ['In progress', in_progress_tasks_count],
      ['Done', done_tasks_count]
    ]);

    // Set chart options
    var options = {'title':'Tasks Status',
                   'width':400,
                   'height':300};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.PieChart(chart_div);
    chart.draw(data, options);
  }

%h1 Dashboard
%center
  %h5 Task Chart (won't be displayed unless connected to internet)
  #chart_div{:data => {:new => @new_tasks_count, :inprogress => @in_progress_tasks_count, :done => @done_tasks_count}}
%br
- if current_user.is_admin?
  %table.table.table-blue
    %th Status
    - @developers.each do |developer|
      %th= developer.name
    %tr
      %td NEW
      - @developers.each do |developer|
        %td= developer.new_tasks.pluck(:name)
    %tr
      %td IN PROGRESS
      - @developers.each do |developer|
        %td= developer.in_progress_tasks.pluck(:name)

    %tr
      %td DONE
      - @developers.each do |developer|
        %td= developer.done_tasks.pluck(:name)
- else
  %table.table.table-blue
    %th Status
    - @projects.each do |project|
      %th= project.name
    %tr
      %td NEW
      - @projects.each do |project|
        %td= project.new_tasks.pluck(:name)
    %tr
      %td IN PROGRESS
      - @projects.each do |project|
        %td= project.in_progress_tasks.pluck(:name)

    %tr
      %td DONE
      - @projects.each do |project|
        %td= project.done_tasks.pluck(:name)